name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Replace with your desired branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your requirements file name

      - name: Build the application
        run: |
          python app.py  # Replace with the command to build your Flask application

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'Muriki Sai Srinivas'
          git config --global user.email 'msaisrinivas08@gmail.com'
          git checkout -b gh-pages
          git add .
          git commit -m 'Deploy application'
          git push --force origin gh-pages
